version: "3"

services:
  frontend:
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile.front
    container_name: asyncomm-frontend-vue
    ports:
      - 8080:8080
    volumes:
      - ./frontend-vue:/app/

  api:
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile.api
    container_name: asycomm-backend-django
    ports:
      - 8000:8000
    volumes:
      - ./backend_django:/run/
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DJANGO_SETTINGS_MODULE=backend_django.settings

  mysql:
    build:
      context: .
      dockerfile: ./Dockerfile.data #Dockerfileからビルドすることを示す
    image: asyncomm-mysql
    container_name: asyncomm-database-mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 1s
      retries: 10
      start_period: 3s
      timeout: 20s
    volumes:
      - ./Mysql/db:/var/lib/mysql #初期データをマウントする場所
    ports:
      - 3306:3306
    env_file:
      - db_pass.env
    environment:
      MYSQL_ROOT_PASSWORD: DB_PASSWORD #コンテナ内のMySQLを起動する際のパスワードを設定
      MYSQL_DATABASE: asyncomm
  # ssh:
  #   build: 
  #     context: .
  #     dockerfile: ./Dockerfile.ssh   #Dockerfileからビルドすることを示す
  #   container_name: ssh
  #   ports:
  #     - 50022:22
